#!/usr/bin/env node

/**
 * Setup script to create .env.local file for frontend
 * This script helps users set up their frontend environment variables
 */

const fs = require('fs');
const path = require('path');

const envExampleContent = `# Frontend Environment Configuration
# Generated by setup script

# API Configuration
VITE_API_URL=http://localhost:8000/api

# Supabase Configuration (for client-side operations)
VITE_SUPABASE_URL=https://qphomvhegulifftzirmb.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaG9tdmhlZ3VsaWZmdHppcm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjgxNzksImV4cCI6MjA3MjUwNDE3OX0.W74O4Z-Q-7SXH6x7bq2wghRlae28tZ2qb4VQzz398e4

# App Configuration
VITE_APP_NAME=LeadsFynder
VITE_APP_VERSION=1.0.0

# Development
VITE_DEBUG=true
`;

const envPath = path.join(__dirname, '.env.local');

console.log('🚀 LeadsFynder Frontend Environment Setup');
console.log('========================================\n');

// Check if .env.local already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env.local file already exists.');
  console.log('✅ Frontend environment is already configured.\n');
} else {
  // Write .env.local file
  fs.writeFileSync(envPath, envExampleContent);
  
  console.log('✅ Frontend environment setup complete!');
  console.log('📁 Created .env.local file in frontend directory');
  console.log('\n🔧 Next steps:');
  console.log('1. Run: npm install');
  console.log('2. Run: npm run dev');
  console.log('\n🌐 Your frontend will be available at: http://localhost:3000');
  console.log('🔗 API will be proxied to: http://localhost:8000/api');
}

console.log('\n📋 Environment Variables Set:');
console.log('- VITE_API_URL: http://localhost:8000/api');
console.log('- VITE_SUPABASE_URL: https://qphomvhegulifftzirmb.supabase.co');
console.log('- VITE_SUPABASE_ANON_KEY: [Configured]');
console.log('- VITE_APP_NAME: LeadsFynder');
console.log('- VITE_APP_VERSION: 1.0.0');
console.log('- VITE_DEBUG: true');
