#!/bin/bash

# PostgreSQL to MySQL Schema Converter
# Usage: ./convert-to-mysql.sh schema.sql

if [ $# -eq 0 ]; then
    echo "Usage: $0 <postgresql_schema_file>"
    exit 1
fi

INPUT_FILE=$1
OUTPUT_FILE="${INPUT_FILE%.sql}_mysql.sql"

echo "Converting PostgreSQL schema to MySQL format..."
echo "Input: $INPUT_FILE"
echo "Output: $OUTPUT_FILE"

# Create output file
cat > "$OUTPUT_FILE" << 'EOF'
-- MySQL Schema converted from PostgreSQL
-- Generated by LeadsFynder conversion script

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS `leadsfynder` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `leadsfynder`;

EOF

# Convert the schema
sed -e 's/SERIAL/BIGINT AUTO_INCREMENT/g' \
    -e 's/BIGSERIAL/BIGINT AUTO_INCREMENT/g' \
    -e 's/INTEGER/INT/g' \
    -e 's/TEXT/LONGTEXT/g' \
    -e 's/TIMESTAMP/DATETIME/g' \
    -e 's/BOOLEAN/TINYINT(1)/g' \
    -e 's/DECIMAL/DECIMAL(10,2)/g' \
    -e 's/JSON/JSON/g' \
    -e 's/UNIQUE/UNIQUE KEY/g' \
    -e 's/PRIMARY KEY/PRIMARY KEY/g' \
    -e 's/FOREIGN KEY/FOREIGN KEY/g' \
    -e 's/REFERENCES/REFERENCES/g' \
    -e 's/ON DELETE CASCADE/ON DELETE CASCADE/g' \
    -e 's/ON UPDATE CASCADE/ON UPDATE CASCADE/g' \
    -e 's/DEFAULT now()/DEFAULT CURRENT_TIMESTAMP/g' \
    -e 's/@@map/ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci/g' \
    "$INPUT_FILE" >> "$OUTPUT_FILE"

# Add closing
echo "
COMMIT;" >> "$OUTPUT_FILE"

echo "Conversion completed!"
echo "MySQL schema saved to: $OUTPUT_FILE"
echo ""
echo "To import the schema:"
echo "mysql -u username -p database_name < $OUTPUT_FILE"
